repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
      - id: black-jupyter
  - repo: https://github.com/pycqa/isort
    rev: v5.11.3
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
        additional_dependencies:
          - "prettier-plugin-svelte"
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        args: [--ignore-words=.dictionary.txt]
        exclude: ^(notebooks|poetry.lock|data)|package-lock.json
  - repo: local
    hooks:
      - id: check-versions
        name: check package versions
        entry: python scripts/check_versions.py
        language: python
        always_run: true
