steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull gcr.io/$PROJECT_ID/$REPO_NAME:latest || exit 0"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/$REPO_NAME:latest",
        "--build-arg",
        "VITE_STATIC_HOST=${_VITE_STATIC_HOST}",
        "--cache-from",
        "gcr.io/$PROJECT_ID/$REPO_NAME:latest",
        "app",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:latest"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "$REPO_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:latest"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
images: ["gcr.io/$PROJECT_ID/$REPO_NAME:latest"]
options:
  logging: CLOUD_LOGGING_ONLY
