steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      ["-c", "docker pull gcr.io/$PROJECT_ID/$REPO_NAME-app:latest || exit 0"]
    waitFor: ["-"]
    id: pull-app
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "docker/Dockerfile.app",
        "-t",
        "gcr.io/$PROJECT_ID/$REPO_NAME-app:latest",
        "--build-arg",
        "VITE_STATIC_HOST=${_VITE_STATIC_HOST}",
        "--build-arg",
        "VITE_CACHE_BUCKET=${_VITE_CACHE_BUCKET}",
        "--cache-from",
        "gcr.io/$PROJECT_ID/$REPO_NAME-app:latest",
        ".",
      ]
    waitFor: [pull-app]
    id: build-app
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME-app:latest"]
    waitFor: [build-app]
    id: push-app
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "$REPO_NAME",
        "--image",
        "gcr.io/$PROJECT_ID/$REPO_NAME-app:latest",
        "--region",
        "${_REGION}",
        "--platform",
        "managed",
      ]
    waitFor: [push-app]
    id: deploy-app

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      ["-c", "docker pull gcr.io/$PROJECT_ID/$REPO_NAME-sys:latest || exit 0"]
    waitFor: ["-"]
    id: pull-sys
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "docker/Dockerfile.sys",
        "-t",
        "gcr.io/$PROJECT_ID/$REPO_NAME-sys:latest",
        "--cache-from",
        "gcr.io/$PROJECT_ID/$REPO_NAME-sys:latest",
        ".",
      ]
    waitFor: [pull-sys]
    id: build-sys
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME-sys:latest"]
    waitFor: [build-sys]
    id: push-sys
images:
  [
    "gcr.io/$PROJECT_ID/$REPO_NAME-app:latest",
    "gcr.io/$PROJECT_ID/$REPO_NAME-sys:latest",
  ]
options:
  logging: CLOUD_LOGGING_ONLY
