steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      ["-c", "docker pull gcr.io/$PROJECT_ID/$REPO_NAME-app:latest || exit 0"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "docker/Dockerfile.app",
        "-t",
        "gcr.io/$PROJECT_ID/$REPO_NAME-app:latest",
        "--build-arg",
        "VITE_STATIC_HOST=${_VITE_STATIC_HOST}",
        "--cache-from",
        "gcr.io/$PROJECT_ID/$REPO_NAME-app:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME-app:latest"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "$REPO_NAME",
        "--image",
        "gcr.io/$PROJECT_ID/$REPO_NAME-app:latest",
        "--region",
        "${_REGION}",
        "--platform",
        "managed",
      ]
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      ["-c", "docker pull gcr.io/$PROJECT_ID/$REPO_NAME-sys:latest || exit 0"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "docker/Dockerfile.sys",
        "-t",
        "gcr.io/$PROJECT_ID/$REPO_NAME-sys:latest",
        "--cache-from",
        "gcr.io/$PROJECT_ID/$REPO_NAME-sys:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME-sys:latest"]
images:
  [
    "gcr.io/$PROJECT_ID/$REPO_NAME-app:latest",
    "gcr.io/$PROJECT_ID/$REPO_NAME-sys:latest",
  ]
options:
  logging: CLOUD_LOGGING_ONLY
