version: "3.8"
volumes:
  node_modules:
services:
  nginx:
    image: nginx:stable
    volumes:
      - ./data/:/app/data:ro
      - ./nginx/${NGINX_CONF:-remote}.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4000:4000"
  app:
    build:
      dockerfile: docker/Dockerfile.app
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    command: npm run dev -- --host --port 5173
    ports:
      - "5173:5173"
    depends_on:
      - nginx
    environment:
      - VITE_STATIC_HOST=http://nginx:4000
  redoc:
    image: redocly/redoc
    restart: always
    volumes:
      - ./app/static/openapi/:/usr/share/nginx/html/openapi/
    environment:
      - SPEC_URL=openapi/openapi.yaml
    ports:
      - "4001:80"
