version: "3.8"
volumes:
  node_modules:
services:
  nginx:
    image: nginx:stable
    volumes:
      - ./data/:/app/data:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4000:4000"
  app:
    build:
      context: app
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    command: npm run dev -- --host --port ${PORT}
    ports:
      - "5173:5173"
    depends_on:
      - nginx
    environment:
      - VITE_STATIC_HOST=http://nginx:4000
      - PORT=5173
