[tool.poetry]
name = "manga-recsys"
version = "0.1.0"
description = ""
authors = ["geospiza <geospiza@protonmail.com>"]
readme = "README.md"
packages = [{include = "manga_recsys"}]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
pandas = "^1.5.2"
pyarrow = "^10.0.1"


[tool.poetry.group.dev.dependencies]
jupyterlab = "^3.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
