openapi: 3.0.0
info:
  title: manga-recsys
  description: API routes for recommendation
  version: 1.0.0
servers:
  - url: https://manga-recsys.geospiza.me
    description: Production instance
  - url: http://localhost:5173
    description: Local docker-compose instance
paths:
  /:
    get:
      summary: home
      responses:
        "200":
          description: OK
          content:
            text/html; charset=utf-8:
              schema:
                type: string
  /api/v1/models/tag-rules/association_rules.json:
    get:
      summary: association rules
  /api/v1/models/tag-rules/freq_itemsets.json:
    get:
      summary: frequent itemsets
  # TODO: metadata, group-manga, manga-tags-word2vec
